# AIM ---------------------------------------------------------------------
# update the annotation of the demyelination classification
# the calssification update has been generated by Gianni under the supervision of Martina and Sofia

# libraries ---------------------------------------------------------------
library(Seurat)
library(tidyverse)
library(patchwork)

# read in the data --------------------------------------------------------
scobj <- readRDS("../../out/object/analysis_R44/26_sobj_integrated_cleanup_manualAnnotation.rds")
Idents(scobj) <- "cell_id"

# show the UMAP with the former anntoation
DimPlot(scobj,label = T)

# read in the new metadata
meta_new <- read_csv("../../data/20260416_spinal_demyelination_update.csv")

# wrangling ---------------------------------------------------------------
# update the classification of the new metedata
# after chatting with martina she recommened to also generate some ad hoc categories for the demyelination classification
meta_new2 <- meta_new %>%
  mutate(
    demye_WM_class = case_when(is.na(demye_WM_prop) ~ NA,
                               diagnosis == "Non-demented control" ~ "no",
                               demye_WM_prop > 0.3 ~ "high",
                               TRUE ~ "low") %>%
      factor(levels = c("no", "low", "high")),
    
    demye_tot_class = case_when(is.na(demye_tot_prop) ~ NA,
                                diagnosis == "Non-demented control" ~ "no",
                                demye_tot_prop > 0.3 ~ "high",
                                TRUE ~ "low") %>%
      factor(levels = c("no", "low", "high")),
    
    demye_GM_class = case_when(is.na(demye_GM_prop) ~ NA,
                               diagnosis == "Non-demented control" ~ "no",
                               demye_GM_prop > 0.5 ~ "high",
                               TRUE ~ "low") %>%
      factor(levels = c("no", "low", "high")))

# compare the metrics of the cells based on the cutoffs
lapply(c("demye_WM_class","demye_tot_class","demye_GM_class"), function(x){
  meta_new2 %>%
    group_by(.data[[x]]) %>%
    summarise(n = n())
})

# calculate the median per metric
meta_new2 %>%
  filter(diagnosis == "Multiple sclerosis") %>%
  summarise(med_GM_prop = median(GM_prop),
            med_demye_WM_prop = median(demye_WM_prop,na.rm = T),
            med_demye_GM_prop = median(demye_GM_prop,na.rm = T),
            med_demye_tot_prop = median(demye_tot_prop,na.rm = T))

# summarise the metadata
meta_old <- scobj@meta.data %>%
  data.frame() %>%
  rownames_to_column("barcodes")

# meta_old_summary <- meta_old %>%
#   group_by(original_sample_name,sample_id,autopsy,sex,age,location,diagnosis) %>% 
#   summarise()
# 
# write_tsv(meta_old_summary,"../../out/table/analysis_R44/001_meta_old_summary.tsv")

# add the new metadata to the samples using the original_sample_name
# shape it to be acceptable by AddMetaData
meta_new_fix <- meta_old %>%
  left_join(meta_new2 %>% select(-c(sample_id,autopsy,sex,age,location,diagnosis))) %>%
  select(barcodes,sequencing,GM_prop,demye_WM_prop,demye_WM_class,demye_GM_prop,demye_GM_class,demye_tot_prop,demye_tot_class) %>%
  column_to_rownames("barcodes")

# add the new metatarsal to the original object
sobj_update <- AddMetaData(scobj,meta_new_fix)

# confirm the addition
# use the old classification
sobj_update@meta.data %>%
  group_by(original_sample_name,demyelination_short) %>%
  summarise(n = n(),
            GM_prop = mean(GM_prop),
            demye_WM_prop = mean(demye_WM_prop),
            demye_GM_prop = mean(demye_GM_prop),
            demye_tot_prop = mean(demye_tot_prop)) %>%
  pivot_longer(names_to = "var",values_to = "prop",-c(original_sample_name,demyelination_short,n)) %>%
  ggplot(aes(x = demyelination_short,y=prop)) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitter(width = 0.2,height = 0)) + 
  facet_wrap(~var,scales = "free") + theme_bw() + theme(strip.background = element_blank())

# use the new classification
# sobj_update@meta.data %>%
#   group_by(original_sample_name,demye_WM_class) %>%
#   summarise(n = n(),
#             demye_WM_prop = mean(demye_WM_prop,na.rm = T)) %>%
#   pivot_longer(names_to = "var",values_to = "prop",-c(original_sample_name,demye_WM_class,n)) %>%
#   filter(!is.na(demye_WM_class)) %>%
#   ggplot(aes(x = demye_WM_class,y=prop)) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitter(width = 0.2,height = 0)) + 
#   facet_wrap(~var,scales = "free") + theme_bw() + theme(strip.background = element_blank())

# x <- "demye_WM"
lapply(c("demye_WM","demye_GM","demye_tot"),function(x){
  # define the column name
  col_id <- paste0(x,"_prop")
  
  # run the aggregation
  sobj_update@meta.data %>%
    group_by(original_sample_name,.data[[paste0(x,"_class")]]) %>%
    summarise(n = n(),
              !!col_id := mean(.data[[paste0(x,"_prop")]],na.rm = T)) %>%
    pivot_longer(names_to = "var",values_to = "prop",-c(original_sample_name,.data[[paste0(x,"_class")]],n)) %>%
    filter(!is.na(.data[[paste0(x,"_class")]])) %>%
    ggplot(aes(x = .data[[paste0(x,"_class")]],y=prop)) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitter(width = 0.2,height = 0)) + 
    facet_wrap(~var,scales = "free") + theme_bw() + theme(strip.background = element_blank())
}) %>%
  wrap_plots()


# save the objects --------------------------------------------------------

# save the object
saveRDS(sobj_update,"../../out/object/analysis_R44/001_sobj_integrated_cleanup_manualAnnotation_updateDemyelination.rds")
